[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
red = { path = "../../../rust/red" }
common = { path = "../common" }
clap = { version = "4.4", features = ["derive"] }
libc = "0.2"
